### ISSUE TITLE
Allow setting file location in config

### ISSUE THREAD

**Issue by Khikki** [IAmSneak/diamond-economy#13]
Hi, is it possible to add support for SQL/MYSQL? For example, I have 3 linked servers, I would like to use your mod :)

**Comment by IAmSneak** [comment]
I imagine that would be possible, I'll look into it when I get the chance.

**Comment by IAmSneak** [comment]
This feels like something outside of the scope of this base mod. I'm internally changing a lot of things so I'll add support for alternative SQL types, that way I can make a seperate extension mod for this in the future.

**Comment by Khikki** [comment]
it will not work just to add the ability to choose where to store the sql database?

**Comment by IAmSneak** [comment]
Yeah that probably would work

**Comment by IAmSneak** [comment]
Probably later today or tomorrow. I changed almost everything internally which completely breaks my chest shop plugin, so I need to fix that up when I get home from school.

**Comment by IAmSneak** [comment]
release is now out

**Comment by Khikki** [comment]
how how about an update? modrinth or releases, I couldn't build it.

**Comment by IAmSneak** [comment]
I just added the links to readme, I'm not going to continue using github releases until I can automate them.
[curseforge](https://www.curseforge.com/minecraft/mc-mods/diamond-economy)
[modrinth](https://modrinth.com/mod/diamond-economy)
