### ISSUE TITLE
[Compatibility] Shoppy

### ISSUE THREAD

**Issue by Balakay420** [IAmSneak/diamond-economy#20]
Please add compatibility for shoppy (https://www.curseforge.com/minecraft/mc-mods/shoppy)

**Comment by Balakay420** [comment]
Is there an update on this? :D

**Comment by IAmSneak** [comment]
sorry you had got me is an unmotivated time. it looks like this would need to be added from shoppy's side

**Comment by Balakay420** [comment]
No worries, could you put an issue in on their GitHub for me? Thanks!

**Comment by IAmSneak** [comment]
should work in the upcoming update when using the common bridge mod
